// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf_contracts/contract.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ffi.contract;

@kotlin.jvm.JvmName("-initializebytearrayWrongLengthError")
public inline fun bytearrayWrongLengthError(block: ffi.contract.BytearrayWrongLengthErrorKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.BytearrayWrongLengthError =
  ffi.contract.BytearrayWrongLengthErrorKt.Dsl._create(ffi.contract.Contract.BytearrayWrongLengthError.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ffi.contract.BytearrayWrongLengthError`
 */
public object BytearrayWrongLengthErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ffi.contract.Contract.BytearrayWrongLengthError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ffi.contract.Contract.BytearrayWrongLengthError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ffi.contract.Contract.BytearrayWrongLengthError = _builder.build()

    /**
     * `string field_name = 1;`
     */
    public var fieldName: kotlin.String
      @JvmName("getFieldName")
      get() = _builder.getFieldName()
      @JvmName("setFieldName")
      set(value) {
        _builder.setFieldName(value)
      }
    /**
     * `string field_name = 1;`
     */
    public fun clearFieldName() {
      _builder.clearFieldName()
    }

    /**
     * `uint32 expected_length = 2;`
     */
    public var expectedLength: kotlin.Int
      @JvmName("getExpectedLength")
      get() = _builder.getExpectedLength()
      @JvmName("setExpectedLength")
      set(value) {
        _builder.setExpectedLength(value)
      }
    /**
     * `uint32 expected_length = 2;`
     */
    public fun clearExpectedLength() {
      _builder.clearExpectedLength()
    }

    /**
     * `uint32 actual_length = 3;`
     */
    public var actualLength: kotlin.Int
      @JvmName("getActualLength")
      get() = _builder.getActualLength()
      @JvmName("setActualLength")
      set(value) {
        _builder.setActualLength(value)
      }
    /**
     * `uint32 actual_length = 3;`
     */
    public fun clearActualLength() {
      _builder.clearActualLength()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ffi.contract.Contract.BytearrayWrongLengthError.copy(block: ffi.contract.BytearrayWrongLengthErrorKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.BytearrayWrongLengthError =
  ffi.contract.BytearrayWrongLengthErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

