// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf_contracts/contract.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ffi.contract;

@kotlin.jvm.JvmName("-initializedeoxysIIDecryptRequest")
public inline fun deoxysIIDecryptRequest(block: ffi.contract.DeoxysIIDecryptRequestKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.DeoxysIIDecryptRequest =
  ffi.contract.DeoxysIIDecryptRequestKt.Dsl._create(ffi.contract.Contract.DeoxysIIDecryptRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Decrypt
 * ```
 *
 * Protobuf type `ffi.contract.DeoxysIIDecryptRequest`
 */
public object DeoxysIIDecryptRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ffi.contract.Contract.DeoxysIIDecryptRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ffi.contract.Contract.DeoxysIIDecryptRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ffi.contract.Contract.DeoxysIIDecryptRequest = _builder.build()

    /**
     * `bytes private_key = 1;`
     */
    public var privateKey: com.google.protobuf.ByteString
      @JvmName("getPrivateKey")
      get() = _builder.getPrivateKey()
      @JvmName("setPrivateKey")
      set(value) {
        _builder.setPrivateKey(value)
      }
    /**
     * `bytes private_key = 1;`
     */
    public fun clearPrivateKey() {
      _builder.clearPrivateKey()
    }

    /**
     * `bytes encrypted_data = 2;`
     */
    public var encryptedData: com.google.protobuf.ByteString
      @JvmName("getEncryptedData")
      get() = _builder.getEncryptedData()
      @JvmName("setEncryptedData")
      set(value) {
        _builder.setEncryptedData(value)
      }
    /**
     * `bytes encrypted_data = 2;`
     */
    public fun clearEncryptedData() {
      _builder.clearEncryptedData()
    }

    /**
     * `bytes node_public_key = 3;`
     */
    public var nodePublicKey: com.google.protobuf.ByteString
      @JvmName("getNodePublicKey")
      get() = _builder.getNodePublicKey()
      @JvmName("setNodePublicKey")
      set(value) {
        _builder.setNodePublicKey(value)
      }
    /**
     * `bytes node_public_key = 3;`
     */
    public fun clearNodePublicKey() {
      _builder.clearNodePublicKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ffi.contract.Contract.DeoxysIIDecryptRequest.copy(block: ffi.contract.DeoxysIIDecryptRequestKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.DeoxysIIDecryptRequest =
  ffi.contract.DeoxysIIDecryptRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

