// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf_contracts/contract.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ffi.contract;

@kotlin.jvm.JvmName("-initializedeoxysIIEncryptRequest")
public inline fun deoxysIIEncryptRequest(block: ffi.contract.DeoxysIIEncryptRequestKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.DeoxysIIEncryptRequest =
  ffi.contract.DeoxysIIEncryptRequestKt.Dsl._create(ffi.contract.Contract.DeoxysIIEncryptRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Encrypt
 * ```
 *
 * Protobuf type `ffi.contract.DeoxysIIEncryptRequest`
 */
public object DeoxysIIEncryptRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ffi.contract.Contract.DeoxysIIEncryptRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ffi.contract.Contract.DeoxysIIEncryptRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ffi.contract.Contract.DeoxysIIEncryptRequest = _builder.build()

    /**
     * `bytes private_key = 1;`
     */
    public var privateKey: com.google.protobuf.ByteString
      @JvmName("getPrivateKey")
      get() = _builder.getPrivateKey()
      @JvmName("setPrivateKey")
      set(value) {
        _builder.setPrivateKey(value)
      }
    /**
     * `bytes private_key = 1;`
     */
    public fun clearPrivateKey() {
      _builder.clearPrivateKey()
    }

    /**
     * `bytes data = 2;`
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * `bytes data = 2;`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * `bytes node_public_key = 3;`
     */
    public var nodePublicKey: com.google.protobuf.ByteString
      @JvmName("getNodePublicKey")
      get() = _builder.getNodePublicKey()
      @JvmName("setNodePublicKey")
      set(value) {
        _builder.setNodePublicKey(value)
      }
    /**
     * `bytes node_public_key = 3;`
     */
    public fun clearNodePublicKey() {
      _builder.clearNodePublicKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ffi.contract.Contract.DeoxysIIEncryptRequest.copy(block: ffi.contract.DeoxysIIEncryptRequestKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.DeoxysIIEncryptRequest =
  ffi.contract.DeoxysIIEncryptRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

