// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobuf_contracts/contract.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ffi.contract;

@kotlin.jvm.JvmName("-initializedeoxysIIDecryptResponse")
public inline fun deoxysIIDecryptResponse(block: ffi.contract.DeoxysIIDecryptResponseKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.DeoxysIIDecryptResponse =
  ffi.contract.DeoxysIIDecryptResponseKt.Dsl._create(ffi.contract.Contract.DeoxysIIDecryptResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ffi.contract.DeoxysIIDecryptResponse`
 */
public object DeoxysIIDecryptResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ffi.contract.Contract.DeoxysIIDecryptResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ffi.contract.Contract.DeoxysIIDecryptResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ffi.contract.Contract.DeoxysIIDecryptResponse = _builder.build()

    /**
     * `.ffi.contract.DeoxysIIDecryptSuccessResponse success = 1;`
     */
    public var success: ffi.contract.Contract.DeoxysIIDecryptSuccessResponse
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `.ffi.contract.DeoxysIIDecryptSuccessResponse success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
    /**
     * `.ffi.contract.DeoxysIIDecryptSuccessResponse success = 1;`
     * @return Whether the success field is set.
     */
    public fun hasSuccess(): kotlin.Boolean {
      return _builder.hasSuccess()
    }

    /**
     * `.ffi.contract.DeoxysIIDecryptFailureResponse failure = 2;`
     */
    public var failure: ffi.contract.Contract.DeoxysIIDecryptFailureResponse
      @JvmName("getFailure")
      get() = _builder.getFailure()
      @JvmName("setFailure")
      set(value) {
        _builder.setFailure(value)
      }
    /**
     * `.ffi.contract.DeoxysIIDecryptFailureResponse failure = 2;`
     */
    public fun clearFailure() {
      _builder.clearFailure()
    }
    /**
     * `.ffi.contract.DeoxysIIDecryptFailureResponse failure = 2;`
     * @return Whether the failure field is set.
     */
    public fun hasFailure(): kotlin.Boolean {
      return _builder.hasFailure()
    }
    public val responseCase: ffi.contract.Contract.DeoxysIIDecryptResponse.ResponseCase
      @JvmName("getResponseCase")
      get() = _builder.getResponseCase()

    public fun clearResponse() {
      _builder.clearResponse()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ffi.contract.Contract.DeoxysIIDecryptResponse.copy(block: ffi.contract.DeoxysIIDecryptResponseKt.Dsl.() -> kotlin.Unit): ffi.contract.Contract.DeoxysIIDecryptResponse =
  ffi.contract.DeoxysIIDecryptResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ffi.contract.Contract.DeoxysIIDecryptResponseOrBuilder.successOrNull: ffi.contract.Contract.DeoxysIIDecryptSuccessResponse?
  get() = if (hasSuccess()) getSuccess() else null

public val ffi.contract.Contract.DeoxysIIDecryptResponseOrBuilder.failureOrNull: ffi.contract.Contract.DeoxysIIDecryptFailureResponse?
  get() = if (hasFailure()) getFailure() else null

